import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const asdfasdf: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};




import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <>
    <Head>
      <title>Brandon Apol</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/tent.png" />
    </Head>
    <div className="relative h-screen">
      <Image
        src="/assets/IMG_2035.JPG"
        alt="Background Image"
        layout="fill"
        objectFit="cover"
        objectPosition="center"
      />
      <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-center text-white">
        <h1 className="text-5xl font-bold mb-6">Welcome to my Portfolio</h1>
        <p className="text-lg mb-8">Here you'll find examples of my work in web development and design.</p>
        <button className="bg-white text-black px-8 py-4 text-lg font-medium rounded-full transition-colors duration-300 hover:bg-black hover:text-white">View Blog</button>
      </div>
    </div>
    </>
  )
}

export default Home
